version: '3.8'

services:
  db:
    image: postgres:15
    container_name: riffly-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rifflypostgresuser
      POSTGRES_PASSWORD: rifflypostgrespassword
      POSTGRES_DB: rifflypostgresdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
