version: '3.8'

services:
  db:
    image: postgres:15
    container_name: riffly-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rifflypostgresuser
      POSTGRES_PASSWORD: rifflypostgrespassword
      POSTGRES_DB: rifflypostgresdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: riffly-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: rifflyminioadmin
      MINIO_ROOT_PASSWORD: rifflyminiopassword
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  postgres_data:
  minio_data:
